SET SEARCH_PATH TO MS;

DROP TABLE IF EXISTS police_control CASCADE;
DROP TABLE IF EXISTS radartrap CASCADE;
DROP TABLE IF EXISTS points CASCADE;
DROP TABLE IF EXISTS track CASCADE;
DROP TABLE IF EXISTS motorcycle CASCADE;
DROP TABLE IF EXISTS driver CASCADE;

DROP SCHEMA IF EXISTS ms CASCADE;

COMMIT;